#!bin/bash

curl  "https://raw.githubusercontent.com/ssnjrthegr8/tegbzn/master/temp.tegbzn.conf" -o /home/nzbget/nzbget.conf && 
echo 'nzbget config loaded' || { echo 'ERROR: unable to get nzbget config' ; exit 1; }
# Rewrites certain options in nzbget.conf:

home='\/home\/nzbget\/maindir\/'
extensions='gclone_pp.py'
formauth='yes'
PORT='6791'
CTRL_USERNAME='itsyoursuparibhai'
CTRL_PASS='suparibhaikeaagekoibolsaktahaikya'

sed -i \
    -e 's/\(ControlPort=\).*/\1'$PORT'/' \
    -e 's/\(ControlUsername=\).*/\1'$CTRL_USERNAME'/' \
    -e 's/\(ControlPassword=\).*/\1'$CTRL_PASS'/' \
    -e 's/\(MainDir=\).*/\1'$home'/' \
    -e 's/\(Extensions=\).*/\1'$extensions'/' \
    -e 's/\(FormAuth=\).*/\1'$formauth'/' \
    /home/nzbget/nzbget.conf

./nzbget/nzbget -o ControlPort=$PORT -D

python3 ping.py
